### ISSUE TITLE
joptsimple.OptionMissingRequiredArgumentException: Option ['topic'] requires an argument

### ISSUE THREAD

**Issue by amitoj** [stealthly/scala-kafka#12]
First attempt to connect to kafka failed with following error message

macbook:kafka_2.8.0-0.8.1.1 amitojsh$ bin/kafka-console-producer.sh --broker-list 192.168.86.10:9092 --topic
Exception in thread "main" joptsimple.OptionMissingRequiredArgumentException: Option ['topic'] requires an argument
    at joptsimple.RequiredArgumentOptionSpec.detectOptionArgument(RequiredArgumentOptionSpec.java:49)
    at joptsimple.ArgumentAcceptingOptionSpec.handleOption(ArgumentAcceptingOptionSpec.java:209)
    at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:405)
    at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:55)
    at joptsimple.OptionParser.parse(OptionParser.java:392)
    at kafka.producer.ConsoleProducer$.main(ConsoleProducer.scala:110)
    at kafka.producer.ConsoleProducer.main(ConsoleProducer.scala)

**Comment by mgainty** [comment]
which repo contins joptsimple?
Thanks
